name: Release
on:
  workflow_dispatch:
concurrency:
  group: builds-sky-workflow-lint
  cancel-in-progress: false

jobs:
  release:
    runs-on:
      group: builds
      labels: [self-hosted, macOS, ARM64]
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
